### PR TITLE
Additional refactoring for caching.

### PR DESCRIPTION
**Pull request by JakeGinnivan**
Builds on the ideas introduced in #1100

@DanielRose can you have a look at the additional refactorings and let me know if you have any further suggestions.

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
Open question: Should we cache `GetBranchesContainingCommit`, I don't know how many times it is hit with the same commit during a run. Would be interesting to see.

**Comment by JakeGinnivan** [comment]
// @asbjornu

**Comment by asbjornu** [comment]
@JakeGinnivan: We should probably do a little profile. I don't have time at the moment, but perhaps @cvpcs or @DanielRose can help out with that?

**Comment by DanielRose** [comment]
@asbjornu @JakeGinnivan I'll try running through a profiler tomorrow.

**Pull request merged**
